### ISSUE TITLE
Include account labels value in id token contents

### ISSUE THREAD

**Issue by andreaceccanti** [indigo-iam/iam#385]
This will allow exposing information like the CERN person ID to integrated applications

**Comment by vokac** [comment]
What is the status of providing info from account labels via SCIM? This is a blocker for us to move away from VOMS Admin API and rely only on IAM SCIM. Do you think we can expect this functionality in coming months (optimally deployed on CERN production IAM instance)?

**Comment by rmiccoli** [comment]
Solved in commit 1b32c9a.

**Comment by enricovianello** [comment]
Example of usage in your application.yml:

```yaml
iam:
  token-enhancer:
    include-labels:
      - label:
          name: label-name-to-be-included-as-an-added-claim
          prefix: label-prefix
        claim_name: added-claim
```
