### ISSUE TITLE
Add account's list of labels to IndigoUser SCIM schema

### ISSUE THREAD

**Issue by enricovianello** [indigo-iam/iam#450]
We want the user's labels to be available through the SCIM endpoint.
In order to do this we could add them to the urn:indigo-dc:scim:schemas:IndigoUser schema.
Investigate if it's also the case to add them to the /iam/account/search endpoint returned info.

**Comment by enricovianello** [comment]
duplicate of https://github.com/indigo-iam/iam/issues/385

**Comment by rmiccoli** [comment]
Solved in commit c1759955.

**Comment by enricovianello** [comment]
Example of usage on your application.yml:

```yaml
scim:
  include_labels:
    - name: label-name-to-be-included
      prefix: label-prefix
```
