### ISSUE TITLE
Fix web interface for token lifetime

### ISSUE THREAD

**Issue by federicaagostini** [indigo-iam/iam#545]
_E.g._, when the token lifetime is set from configuration as follows

```
client-registration:
  allow-for: anyone
  enable: true
  client-defaults:
    default-access-token-validity-seconds: 1200
    default-refresh-token-validity-seconds: 2592000
```

the web interface does not update the default configuration (even if the client configuration takes the correct defaults)

![default-lifetime-web-interface](https://user-images.githubusercontent.com/13579100/208459346-c315cf01-b447-417d-b990-bcaea72e91c3.png)
