### ISSUE TITLE
iam service in restart continuo 

### ISSUE THREAD

**Issue by bl000m** [indigo-iam/iam#654]
Buongiorno, 
 dopo avere docker-compose up il service iam passa in restart continuo e nei logs non ritrovo errori:
 ```
\  \|\   __  \|\   _ \  _   \    
\ \  \ \  \|\  \ \  \\\__\ \  \   
 \ \  \ \   __  \ \  \\|__| \  \  
  \ \  \ \  \ \  \ \  \    \ \  \ 
   \ \__\ \__\ \__\ \__\    \ \__\
    \|__|\|__|\|__|\|__|     \|__|
                                  
IAM version: 1.8.2 
IAM git commit id: 7a027c4

Spring boot version: 2.6.14

2023-10-02 13:17:30.639  INFO 7 --- [           main] it.infn.mw.iam.IamLoginService           : Starting IamLoginService v1.8.2 using Java 17.0.7 on 65cb8e47a352 with PID 7 (/indigo-iam/WEB-INF/classes started by root in /indigo-iam)
2023-10-02 13:17:30.642  INFO 7 --- [           main] it.infn.mw.iam.IamLoginService           : The following 6 profiles are active: "prod", "mysql", "flyway-repair", "oidc", "saml", "registration"
 ___  ________  _____ ______      
|\  \|\   __  \|\   _ \  _   \    
\ \  \ \  \|\  \ \  \\\__\ \  \   
 \ \  \ \   __  \ \  \\|__| \  \  
  \ \  \ \  \ \  \ \  \    \ \  \ 
   \ \__\ \__\ \__\ \__\    \ \__\
    \|__|\|__|\|__|\|__|     \|__|
                                  
IAM version: 1.8.2 
IAM git commit id: 7a027c4

Spring boot version: 2.6.14

2023-10-02 13:18:49.621  INFO 7 --- [           main] it.infn.mw.iam.IamLoginService           : Starting IamLoginService v1.8.2 using Java 17.0.7 on 65cb8e47a352 with PID 7 (/indigo-iam/WEB-INF/classes started by root in /indigo-iam)
2023-10-02 13:18:49.625  INFO 7 --- [           main] it.infn.mw.iam.IamLoginService           : The following 6 profiles are active: "prod", "mysql", "flyway-repair", "oidc", "saml", "registration"
```

di seguito la configurazione del service nel docker-compose.
```
iam-login-service:
    image: indigoiam/iam-login-service:v1.8.2
    container_name: iam-login-service
    ports:
      - 8080:8080
    env_file:
      - env
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./keystore.jks:/keystore.jks:ro
    restart: unless-stopped
    depends_on:
      - mariadb
      - jwtk_generator
    networks:
      - iam
```
A cosa potrebbe essere dovuto il problema?
Grazie per il vostro aiuto
