### ISSUE TITLE
1.8.4: JIT account provisionning not working if IdP doesn't provide given name/last name

### ISSUE THREAD

**Issue by jouvin** [indigo-iam/iam#753]
I tried to configure JIT account provisionning using the following configuration: 

```
  jit-account-provisioning:
    enabled: true
    #trusted-idps: https://idp.universite-paris-saclay.fr/idp
    trusted-idps: all
```

But I get an error if I try to autoprovision an account, authenticating through SAML, see 
[autoprovisionning_upsaclay_error.log](https://github.com/indigo-iam/iam/files/15041330/autoprovisionning_upsaclay_error.log). It happens because the IdP doesn't provide given name and lastname as it is shown when trying to provision the account the traditional way (with validation). 

As for me it is unexpected and it makes the feature not really useful because if using eduGAIN, you'll have a lot of users who cannot provision their account and just receive an error... IMO, when doing JIT provisionning, the user should be able to go through the usual account creation form and to fill the missing mandatory fields. Just it should not be possible to change the email (that must be provided by the IdP).
