### ISSUE TITLE
When local login is hidden, sll=y no longer works

### ISSUE THREAD

**Issue by hshort** [indigo-iam/iam#859]
The documentation (https://indigo-iam.github.io/v/v1.10.0/docs/reference/configuration/local_authn/) specifies that the sll=y link should work even if the local login page is hidden as done below.

```
iam:
  local-authn:
    # possible values for enabled-for: all, vo-admins, none
    enabled-for: vo-admins 
    # possible values: hidden, hidden-with-link, visible
    login-page-visibility: hidden 
```

This is no longer true and the sll=y url becomes unavailable. 
We would like to be able to completely hide this option on the login page but be able to access it if absolutely needed (e.g. for disaster recovery).
